<!-- Modal -->
<div class="modal fade" id="aboutUsModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark-custom text-light">
                <h1 class="navbar-brand fs-5" id="staticBackdropLabel">Laralogger</h1>
                {{-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> --}}
            </div>
            <div class="modal-body">
                <p>
                    Laralogger is a logging management tool for Laravel applications. It offers an easy-to-use interface
                    for viewing, managing, and analyzing log files generated by your application.
                </p>
                <h3>Developer Information</h3>
                <p>
                    Laralogger was developed by Joshua Maurice C. Yaacoub
                </p>
                <p>
                    Follow or contact the developer through the following links:
                </p>
                <!-- Social Media Buttons -->
                <div class="d-flex justify-content-start">
                    <a href="https://github.com/juswaa101" target="_blank" rel="noopener noreferrer"
                        class="btn btn-outline-dark me-2">
                        <i class="fab fa-github"></i> GitHub
                    </a>
                    <a href="https://www.linkedin.com/in/joshua-maurice-yaacoub/" target="_blank"
                        rel="noopener noreferrer" class="btn btn-outline-primary me-2">
                        <i class="fab fa-linkedin"></i> LinkedIn
                    </a>
                    <a href="https://www.facebook.com/joshua.yaacoub33/" target="_blank" rel="noopener noreferrer"
                        class="btn btn-outline-primary">
                        <i class="fab fa-facebook"></i> Facebook
                    </a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
